Upgrades docker.maven.plugin.fabric8 to 0.40.2.
This update avoids an issue in which the fabric8 plugin was unable to
execute due to an API incompatibility.  See below for more detail.

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.36.0:build
(start) on project HikariCP: Execution start of goal
io.fabric8:docker-maven-plugin:0.36.0: build failed: An API incompatibility
was encountered while executing io.fabric8:docker-maven-plugin:0.36.0:build:
java.lang.UnsatisfiedLinkError: could not load FFI provider
jnr.ffi.provider.jffi.Provider